---
title: "top-data-org"
format: html
editor: visual
---

```{r}

# libraries
library(here)
library(data.table)
library(ggplot2)
library(terra)

```

```{r}

### to check whether the following code produces the "matched_recaps_data.csv" file:

## read in raw Rds data
# tmp <- readRDS(file = "C:/Users/jessica.marsh/Documents/CCAMLR/Toothfish/Toothfish_analysis/Data/558_C2_48_2021-12-09_copy.Rds")
# 
# # convert tmp to list of data tables
# tmp_dt <- lapply(tmp, setDT)
# 
# # tag release
# tag_rel <- tmp_dt$OBS_HAUL_TAG_RELEASE
# 
# # linked releases and recaps
# tag_link <- tmp_dt$OBS_HAUL_TAG_LINK
# 
# # subset linked data to TOP and tags that were released and recaptured within 48.3
# tag_link <- tag_link[which(taxon_code_release == 'TOP' & asd_code_release == '483' & asd_code_recapture == '483'), ]
# 
# # create col to id fish with 1 or 2 tags at release
# tag_link[, prop_tag_rel := ifelse(tag_code_2_release == 'NA|NA|NA|NA', 1, 2)]
# 
# # find fish that were released outside of 48.3 using linked data and subset release data to remove these individuals
# excl_tags <- tag_link[!which(asd_code_release == '483'), obs_haul_tag_release_id]
# tag_rel <- tag_rel[!which(obs_haul_tag_release_id %in% excl_tags), ]
# 
# # subset tag releases to TOP
# tag_rel <- tag_rel[which(taxon_code == 'TOP'), ]
# 
# # add season col and vessel name
# tag_rel[, season_ccamlr:= year(date_release)]
# 
# ## identify good matched recaptures using Tim's existing code
# 
# getAllTagRecaptures <- function(tmp_dt){
#   recaptures <- merge(tmp_dt$OBS_HAUL, tmp_dt$OBS_HAUL_TAG_RECAPTURE, all.y=TRUE, by= "obs_haul_id")
#   recaptures$season_ccamlr_recapture <- recaptures$season_ccamlr  #Get rid of NAs from recaps that don't match effort
#   recaptures
# }
# 
# #Get all recaptures of TOP in 483
# recs <- getAllTagRecaptures(tmp_dt)
# recs <- subset(recs, taxon_code=="TOP" & asd_code=="483")
# 
# #Merge onto CCAMLR link table
# recaptures.all <-  merge(tmp_dt$OBS_HAUL_TAG_LINK, recs, all.y=TRUE, by= "obs_haul_tag_recapture_id")
# table(table(recaptures.all$obs_haul_tag_recapture_id))  ##Duplicate matches
# recaptures.all <- subset(recaptures.all, !duplicated(obs_haul_tag_recapture_id))   #Keep just the first match, maybe think of a better system in future
# 
# ## note no. of duplicates removed
# 
# #Find good matches 
# recaptures.all$matched <- ifelse(recaptures.all$taglink_tagcount ==1, recaptures.all$taglink_score >= 3, recaptures.all$taglink_score >= 5)
# recaptures.all$matched <- ifelse(is.na(recaptures.all$matched), FALSE, recaptures.all$matched)
# table(table(recaptures.all$obs_haul_tag_recapture_id))  #Frequency of matches
# 
# # frequency of matches?
# table(recaptures.all$matched)
# 
# # table of tag count by score
# table(recaptures.all$taglink_tagcount, recaptures.all$taglink_score)
# 
# # subset to matched individuals
# match_tag <- as.data.table(subset(recaptures.all, matched == 'TRUE'))
# 
# # check taxon and asd code
# table(match_tag$taxon_code_release)
# table(match_tag$asd_code_release)
# table(match_tag$asd_code_recapture)
# table(match_tag$taxon_code_recapture)
# 
# # subset to TOP and 483 releases only (recaptures only TOP and 483)
# match_tag <- match_tag[which(taxon_code_release == 'TOP' & asd_code_release == '483'), ]


# read in matched tag data
tags <- fread(here("matched_recaps_data.csv"))

# reduce to cols of interest
tags <- tags[, c("season_ccamlr_release", "length_total_release_cm", "latitude_release", "longitude_release", "length_total_recapture_cm", "days_at_liberty", "sex_code_recapture", "longitude_recapture.x", "latitude_recapture.x", "season_ccamlr_recapture.x", "date_release", "date_recapture.x")]

# remove rows where days at liberty == 0
tags <- tags[!which(days_at_liberty == 0), ]

# calculate specific growth rate
tags[, specific_growth_rate := ((log(length_total_recapture_cm) - log(length_total_release_cm))/days_at_liberty)*100]

# remove rows where specific_growth_rate = NA
tags <- tags[!which(is.na(specific_growth_rate)), ]

# subset to F/M sexes
tags <- tags[which(sex_code_recapture %in% c('F', 'M')), ]

# plot growth rates for fish caught < 2 years at liberty
ggplot(tags[which(days_at_liberty < 730), ], aes(x = length_total_release_cm, y = specific_growth_rate)) +
  geom_point(pch = 21) +
  facet_wrap(~sex_code_recapture) +
  theme_bw()

### temperature data

# r <- rast("TOP_maturity_paper/data/cmems_bottom_temp.nc")
# plot(r[[1]])
# ext(r)
# cat(crs(r), "\n")
# dim(r)
# xy <- rbind(c(-35, -54), c(-35, -54))
# p <- vect(xy, crs="+proj=longlat +datum=WGS84")
# v <- t(extract(r, p))
# plot(v[-1, 1], type = "l")

# change resolution
r <- rast("TOP_maturity_paper/data/cmems_bottom_temp.nc")
r2 <- r
res(r2) <- c(0.2, 0.2)
r2 <- resample(r, r2)

# extract data for tag release location
p <- as.data.table(extract(r2, tags[, .(longitude_release, latitude_release)]))
colnames(p) <- c('id', as.character(time(r2)))

pp <- melt(p, id.vars = "id", variable.name = "date", value.name = "bottom_temp")
#pp$id <- factor(pp$id)
pp$Date <- as.Date(pp$date)

# match tag date release and recapture with pp
tags[, id := 1:.N]

temps <- pp[tags, on = .(id, Date >= date_release, Date <= date_recapture.x)]

colnames(temps)[c(4,5)] <- c('release_date', 'recapture_date')

# save out temps
write.csv(temps, here('Data/bottom_temp_with_tags.csv'))

# get average temp for time at liberty
av_temp <- temps[, .(av_temp = mean(bottom_temp)), by = .(id)]

# add average temp into tag dt
tags[, av_temp := av_temp$av_temp]

# write out tags with av_temp
write.csv(tags, here('Data/tags_with_av_temp.csv'))

```
